export {default as Splash} from './Splash';
export {default as Login} from './Login';
export {default as Onboarding} from './Onboarding';
export {default as RegisterOnBoarding} from './RegisterOnBoarding';
export {default as RegisterSignup} from './RegisterSignup';
export {default as MainPage} from './MainPage';
export {default as Cart} from './Cart';
export {default as Schedule} from './Schedule';
export {default as Account} from './Account';
